### ISSUE TITLE
[Onlyfans] No videos scraped

### ISSUE THREAD

**Issue by kraddock** [DIGITALCRIMINALS/OnlyFans#397]
Latest version, no errors , says Archive Completed in 15.5 Minutes, but...

There are 0 videos, only photos... 

When selecting videos only, no videos are scraped (but are found)

**Comment by wobbleninja** [comment]
It won't download anything for me. It creates the folder of the "model" and the subfolders (Metadata, Posts, Profile, Stories)  and it only downloads the header and the avatar photos inside 'Profile' folder. Nothing else.

Not sure if that's the same issue but I don't ever get pics. Only the avatar and header.

Also, when the script is supposedly finished, it asks me what I want to download from another random girl on my list and I never actually chose that. I only selected one specific girl.

Tested on both free and paid pages.

**Comment by rafaelsousa221** [comment]
same here

**Comment by Bun-Bun** [comment]
I also have the issue where only the profile photos and metadata are downloaded. Folders are created but nothing is downloaded. 

running python 3.10.3 and the latest OnlyFans Downloader script.

No errors displayed even when invoking the script with -v

**Comment by masteraaran** [comment]
Just started having the same issue. 
I'm going to describe the process I went through today in case that helps to troubleshoot:

- I had previously downloaded a model from OF in February. So the latest content at the time was February 15th. I had since moved the main content (images/videos) out of the folder, but left the folder structure under '.sites'.
- Today I wanted to capture all the content since that previous scrape. I started OFDS and it appeared to be working, pulling images and videos, but I noticed that it started at the same date as previously, February 15th. 
- I deleted the folder structure completely, thinking that maybe the previous metadata was fucking with it.
- The script recreated the folder structure, but refused to download content. 
- I updated the script and it stopped working, just crashed immediately. 
- I replaced the files with the files from the previous zip version that I had downloaded. Still didn't work. 
- I ran the script through a separate CMD Prompt, rather than double-clicking the .py file, and got an error about missing 'orjson'. So I ran 'pip install orjson'. It downloaded.
- Script now opens and asks me to update my config.json file. I checked to make sure that my file naming formats were correct and I saved the file. 
- Proceeded normally with the script options.
- The script scrapes the metadata for the model very fast, then says 'Scrape Completed' and tries to move on to another model that I did not select.

**Comment by masteraaran** [comment]
Making a new comment because I just got it working again. 

So, what I did was edit the config file and tell it not to scrape messages, and not to scrape paid content. The model I'm scraping doesn't post paid/ppv content so I didn't need that, and I manually download any videos sent to me in my messages anyway. 

This means that there seems to be a problem with the paid scraping. My theory is this: It scrapes the metadata for the free content first for the model you have selected. Then it says 'Scrape Complete' and it tries to move on to the paid content. It finishes the paid content, but then instead of initiating the download, it tries to scrape the next model in your list too. 

So by disabling the paid content, it forces it to scrape the free content, and then download it, without checking for any/all paid content.

**Comment by d3ibis** [comment]
> > So, what I did was edit the config file and tell it not to scrape messages, and not to scrape paid content.
> > So by disabling the paid content, it forces it to scrape the free content, and then download it, without checking for any/all paid content.
> 
> _**TLDR: Temporarily for a solution until we get an official fix, edit your config.json under .settings folder and change it so it won't scrape messages (from true to false). It'll still scrape messages, nevertheless.**_
> 
> Okay, hold up. I did the same but here's the twist. I went into the config.json and I changed under scrape the messages and the paid to false. This way the script works BUT it actually goes and downloads the paid content AND the messages...
> 
> I tried on a free account which has paid PPVs and wall posts that I actually purchased and it downloaded them normally. It made both Free and Paid folders under Messages and Posts folders and grabbed **everything**, EVEN the paid stuff.
> 
> At first, I missed that you disabled the messages too. And I only set the paid content to false which didn't work. Then I set both messages and paid to false and it works. Then I even tried to set messages to false and paid to true. And it still works. So it seems only the messages is doing the problem so if you put this to false, you're good to go.
> 
> EDIT: The girl I mentioned above was the only girl I could have access to download paid content and test this. Even though I already had her old folder, I renamed it and kept it and I re-downloaded again to see how it works. As it seems, it missed one or two posts. My old folder is 793mb and the new folder is 710mb. So for now, this works but you may lose some content. I don't know if it has anything to do with the settings or if the script failed to grab those for other reason.

It's not working for paid content (maybe just me facing this issue). I tried to set messages to false and paid contents to true, still not downloading paid messages, tried both messages and paid to false, same...

My issue is with download in general (after updating the script to latest), not downloading even free contents (even if toggle messages and paid to false) it shows me that there are 2 stories, 15 posts BUT none is downloaded and no progress bar nothing at all with no files at the end.

**Comment by wobbleninja** [comment]
>It's not working for paid content (maybe just me facing this issue). I tried to set messages to false and paid contents to true, still not downloading paid messages, tried both messages and paid to false, same...

Just tried it again to be sure on the model I already tested on my above comment (since currently that's the only one I can test) and it downloaded all paid content I bought. Except it missed a post which I already mentioned above.

For the record, I am on latest script version, I installed poetry and I even reinstalled the requirements from the text file, just to be sure. Also, I'm on Python 3.10.4. My settings are set to scrape messages "false" and scrape paid content "true".

**Comment by d3ibis** [comment]
> > It's not working for paid content (maybe just me facing this issue). I tried to set messages to false and paid contents to true, still not downloading paid messages, tried both messages and paid to false, same...
> 
> Just tried it again to be sure on the model I already tested on my above comment (since currently that's the only one I can test) and it downloaded all paid content I bought. Except it missed a post which I already mentioned above.
> 
> For the record, I am on latest script version, I installed poetry and I even reinstalled the requirements from the text file, just to be sure. Also, I'm on Python 3.10.4. My settings are set to scrape messages "false" and scrape paid content "true".

Just ran updater.py and went to change messages and paid contents to false, also in metadata I changed comments to false, it downloaded finally one of the profiles (free contents). Before it was showing download bar but nothing was downloaded!

I tried with an account with paid contents (in messages) and now downloading normally (even with messages & paid contents switched to false).

Glad it worked after all and contents are downloaded videos and images!

**Comment by jongkhurunn** [comment]
<img width="429" alt="image" src="https://user-images.githubusercontent.com/31549570/164016668-26c974d6-a30f-44d7-ac66-1a85d2ee16e3.png">

same here!

**Comment by yvoictra** [comment]
This also works for me. Thanks!

**Comment by masteraaran** [comment]
I did some more investigating on this when I had some free time. 

**_TL;DR_** - I don't think the script is actually broken, or at least not broken in the way that I assumed. The problem is that it now wants to scrape messages from EVERY chat you have ever been a part of, and it asks about each one before beginning any downloads. This causes a misunderstanding that it should have downloaded content, when in reality it hasn't even started. By disabling message download, it skips over the misunderstanding. (You can also just hit 'Enter/Return' each time it asks, which I think skips the question...)

**_The script should ASK if you want to download all messages, rather than assuming you do want to. Or at the very least have a 'None' option for each model, rather than forcing you to pick a content type._** 

Read on for my long-winded explanation, as I understand it (I'm using ONLYFANS as the example in this, I don't have any other service to test):

**The first thing that must be understood:** The script creates a silent, background, download queue and _must_ finish asking all of it's questions before it actually begins downloading. 

The misunderstanding we are seeing stems from the commit where the dev programmed the script to automatically scrape a record of all chats, regardless of subscription status.   And is compounded by the above-mentioned (silent) download queue.

Here's the script flow:

1. The script asks what subscribed model you want to download, and what content you want. Assuming you choose 'all', it is easy to assume that it would scrape the model's profile, any messages between you and them, and then begin downloading. Instead, it scrapes it into a silent 'queue' and then moves on to it's next stage.
2. The script scrapes paid content - I don't have any paid/PPV content, so I can't test this. But it appears to run through all of your subscribed models (without asking which model you want!) and checks to see if there is paid content, then adds it to the queue. 
3. The script separately scrapes messages - and here's where the problem occurs. It goes through a list of EVERY chat you have EVER had, and asks if you what content you want from those chats. As mentioned in my TL;DR, there should be a query to ask if you even want to do this, or at the very least each model should have an option for 'NONE' rather than forcing us to choose a type of content. I think just hitting 'Enter/Return' on the keyboard will achieve this, but it still makes folders for each model in the site directory. It adds each selection to the queue.

After it scrapes the messages, the queue is finally done being built, and the download will actually begin. I have had it hang here for a LONG-ASS time (like, 30 minutes easy), but I think that might be because the model I'm downloading has like... 16000+ pictures/videos on her account. 

Final thoughts: The script is not verbose enough to explain what it's doing so that all of our horny, one-handed brains can understand. It's somewhat bad user design ( 😆 ). It repeatedly says 'scrape complete' and 'Finished processing' which understandably cause some confusion regarding what it's doing. Again, there should be a choice about whether you want to scrape all messages, and/or a 'NONE' option for each model it asks about. 

Lastly - I wish that there was a way to only UPDATE a model's folder, rather than redownloading all of the content and manually stopping. Maybe there is and I've missed it. If so, someone please enlighten me.

**Comment by Bun-Bun** [comment]
Yes I replied to one of the other threads. It's simply a misunderstanding of how the script works. I agree, it's bad design. 

I worked around it by setting the script to auto select the account, profile and to download everything for every model. Now I just run the script twice a day and it works automatically without a million prompts.

**Comment by JamiDEV** [comment]
> I did some more investigating on this when I had some free time.
> 
> **_TL;DR_** - I don't think the script is actually broken, or at least not broken in the way that I assumed. The problem is that it now wants to scrape messages from EVERY chat you have ever been a part of, and it asks about each one before beginning any downloads. This causes a misunderstanding that it should have downloaded content, when in reality it hasn't even started. By disabling message download, it skips over the misunderstanding. (You can also just hit 'Enter/Return' each time it asks, which I think skips the question...)
> 
> **_The script should ASK if you want to download all messages, rather than assuming you do want to. Or at the very least have a 'None' option for each model, rather than forcing you to pick a content type._**
> 
> Read on for my long-winded explanation, as I understand it (I'm using ONLYFANS as the example in this, I don't have any other service to test):
> 
> **The first thing that must be understood:** The script creates a silent, background, download queue and _must_ finish asking all of it's questions before it actually begins downloading.
> 
> The misunderstanding we are seeing stems from the commit where the dev programmed the script to automatically scrape a record of all chats, regardless of subscription status. And is compounded by the above-mentioned (silent) download queue.
> 
> Here's the script flow:
> 
>     1. The script asks what subscribed model you want to download, and what content you want. Assuming you choose 'all', it is easy to assume that it would scrape the model's profile, any messages between you and them, and then begin downloading. Instead, it scrapes it into a silent 'queue' and then moves on to it's next stage.
> 
>     2. The script scrapes paid content - I don't have any paid/PPV content, so I can't test this. But it appears to run through all of your subscribed models (without asking which model you want!) and checks to see if there is paid content, then adds it to the queue.
> 
>     3. The script separately scrapes messages - and here's where the problem occurs. It goes through a list of EVERY chat you have EVER had, and asks if you what content you want from those chats. As mentioned in my TL;DR, there should be a query to ask if you even want to do this, or at the very least each model should have an option for 'NONE' rather than forcing us to choose a type of content. I think just hitting 'Enter/Return' on the keyboard will achieve this, but it still makes folders for each model in the site directory. It adds each selection to the queue.
> 
> 
> After it scrapes the messages, the queue is finally done being built, and the download will actually begin. I have had it hang here for a LONG-ASS time (like, 30 minutes easy), but I think that might be because the model I'm downloading has like... 16000+ pictures/videos on her account.
> 
> Final thoughts: The script is not verbose enough to explain what it's doing so that all of our horny, one-handed brains can understand. It's somewhat bad user design ( 😆 ). It repeatedly says 'scrape complete' and 'Finished processing' which understandably cause some confusion regarding what it's doing. Again, there should be a choice about whether you want to scrape all messages, and/or a 'NONE' option for each model it asks about.
> 
> Lastly - I wish that there was a way to only UPDATE a model's folder, rather than redownloading all of the content and manually stopping. Maybe there is and I've missed it. If so, someone please enlighten me.

After hours of digging, this was all I needed, figuring this out took me 8 hours.. but it was so worth it mate. I appreciate your hard work and dedication. 
and for anyone wondering..

subscriptions true, messages false, paid_content true and wait. It took a total of 51 mins for me to scrape 4gb of photos. but Id rather that then sit and download them by hand.
