### ISSUE TITLE
Stuck Processing

### ISSUE THREAD

**Issue by BlueCowboyTx** [DIGITALCRIMINALS/OnlyFans#86]
Awesome script, have it running well.

I grabbed the latest version today (11/8) and have it running. The login and data scraping goes smoothly. When I start the download processing though, it updates once and then stops. 

It has stayed at 30% for 2 hours. Is there something additional I need to do to have it continue to process? 
![image](https://user-images.githubusercontent.com/93951488/140826377-ca8b7360-ad72-4c38-9879-bcbbe15838c3.png)

**Comment by DIGITALCRIMINALS** [comment]
No, it should be downloading continuously. Are you using a VPN? Try setting max_threads to 1 in the config.

**Comment by BlueCowboyTx** [comment]
I'm not using a VPN. 
Just switched over to set max_threads to 1. Same issue. Updates once in downloading and then just blocks. 

I appreciate the response and help! Thank you!

**Comment by DIGITALCRIMINALS** [comment]
What's the model username

**Comment by BlueCowboyTx** [comment]
It happens on any models I try.
Model: jasminx

**Comment by DIGITALCRIMINALS** [comment]
I've updated the script, you update via the updater file

**Comment by notjl** [comment]
Great work with the script, I've been using it for 5 months now but I always noticed I had download problems but didn't bat an eye about this problem. There are times where my download is stuck in certain percentages, this time it's on 7%. Everything else is smooth, it's just this problem.

I have no VPN, I tried setting the max_threads to 1 to no avail the problem persists.
![image](https://user-images.githubusercontent.com/58279268/147923340-b2c2a102-ecce-4090-9725-a141645a4acf.png)
